export PATH="${HOME}/bin:${HOME}/.local/bin:${PATH}:${HOME}/.zplug/bin:${PATH}"

export GOROOT=/usr/local/go/
export GOPATH=${HOME}/git/golang_workspace
export PATH="$PATH:$GOROOT/bin"
export PATH="$PATH:$GOPATH/bin"

export GRIDX="$GOPATH/src/github.com/grid-x"

export LC_ALL=de_DE.UTF-8
export LANG=de_de.UTF-8

export HISTFILE=~/.zsh_history
export HISTSIZE=999999999
export SAVEHIST=$HISTSIZE

export LC_ALL=de_DE.UTF-8
export LANG=de_DE.UTF-8
